const products = [
  {
    id:       1,
    name:     'Amethyst Bloom',
    category: 'Sculpted',
    emoji:    '🌹',
    tag:      'Gift',
    image:    'images/products/amethyst bloom.jpg',
    fragrances: [
      { name: 'French Lavender',     price: 749 },
      { name: 'Velvet Rose & Oud',   price: 849 },
      { name: 'Peony & Blush Suede', price: 749 },
      { name: 'Mogra',               price: 849 },
      { name: 'Periwinkle',          price: 749 },
      { name: 'Jasmine',             price: 749 },
    ],
    sizes: [ { label: '70g', priceAdd: 0 } ],
  },
  {
    id:       2,
    name:     'Garden Collection',
    category: 'Sculpted',
    emoji:    '🌿',
    tag:      '',
    image:    'images/products/garden collection.png',
    fragrances: [
      { name: 'Mogra',               price: 499 },
      { name: 'Periwinkle',          price: 399 },
      { name: 'Jasmine',             price: 399 },
      { name: 'Lavender',            price: 449 },
      { name: 'Velvet Rose & Oud',   price: 499 },
      { name: 'Peony & Blush Suede', price: 349 },
    ],
    sizes: [ { label: '70g', priceAdd: 0 } ],
  },
  {
    id:       3,
    name:     'Iced Strawberry Matcha Latte',
    category: 'Container',
    emoji:    '🍂',
    tag:      '',
    image:    'images/products/strawberry latte.jpg',
    fragrances: [
      { name: 'Strawberry frappuccino',          price: 749 },
      { name: 'Mocha cookie crumble frappuccino', price: 799 },
      { name: 'Smooth Vanilla',                  price: 849 },
      { name: 'Matcha latte',                    price: 749 },
    ],
    sizes: [ { label: '120g', priceAdd: 0 } ],
  },
  {
    id:       4,
    name:     'Vanilla Latte',
    category: 'Container',
    emoji:    '🕯️',
    tag:      'Refreshing',
    image:    'images/products/Vanilla Latte.jpeg',
    fragrances: [
      { name: 'Brewed Coffee',        price: 999  },
      { name: 'Pistachio Latte',      price: 1049 },
      { name: 'Caramel Drizzle',      price: 1049 },
      { name: 'White Chocolate Mocha',price: 1099 },
    ],
    sizes: [ { label: '120g', priceAdd: 0 } ],
  },
  {
    id:       5,
    name:     'Iced Coffee Latte',
    category: 'Container',
    emoji:    '🌸',
    tag:      '',
    image:    'images/products/Iced coffee latte.jpg',
    fragrances: [
      { name: 'Caramel Swirl',       price: 799 },
      { name: 'Creamy Milk',         price: 749 },
      { name: 'Light Cocoa',         price: 799 },
      { name: 'Dubai Chocolate Mocha', price: 799 },
    ],
    sizes: [ { label: '120g', priceAdd: 0 } ],
  },
  {
    id:       6,
    name:     'Serene Muse',
    category: 'gift',
    emoji:    '🎁',
    tag:      'Gift',
    image:    'images/products/Serene Muse.jpg',
    fragrances: [
      { name: 'Rose Petals',   price: 699 },
      { name: 'Arabian Secret', price: 799 },
      { name: 'Vanilla Bean',  price: 749 },
      { name: 'Lemongrass',    price: 699 },
    ],
    sizes: [ { label: '80g', priceAdd: 0 } ],
  },
  {
    id:       7,
    name:     'Minted Roses',
    category: 'Pillar',
    emoji:    '🌲',
    tag:      '',
    image:    'images/products/minted roses.jpg',
    fragrances: [
      { name: 'Fresh Eucalyptus', price: 299 },
      { name: 'Rose Petals',      price: 349 },
      { name: 'Lemongrass',       price: 499 },
      { name: 'Mogra',            price: 499 },
      { name: 'Periwinkle',       price: 349 },
      { name: 'Jasmine',          price: 399 },
    ],
    sizes: [ { label: '80g', priceAdd: 0 } ],
  },
  {
    id:       8,
    name:     'Teddy Bloom',
    category: 'Sculpted',
    emoji:    '🧸',
    tag:      'New',
    image:    'images/products/teddy bloom.jpg',
    fragrances: [
      { name: 'Sweet Floral', price: 599 },
      { name: 'Soft Rose',    price: 649 },
    ],
    sizes: [ { label: '70g', priceAdd: 0 } ],
  },
  {
    id:       9,
    name:     'Petal Reverie',
    category: 'Sculpted',
    emoji:    '🌸',
    tag:      'Gift',
    image:    'images/products/petal reverie.jpg',
    fragrances: [
      { name: 'Tulip',           price: 999 },
      { name: 'Lavender',        price: 749 },
      { name: 'Velvet Rose & Oud', price: 999 },
      { name: 'Peony',           price: 749 },
      { name: 'Mogra',           price: 849 },
      { name: 'Periwinkle',      price: 749 },
      { name: 'Jasmine',         price: 749 },
    ],
    sizes: [ { label: '100g', priceAdd: 0 } ],
  },
  {
    id:       10,
    name:     'Berry Blush Spritz',
    category: 'Container',
    emoji:    '🍸',
    tag:      'Limited',
    image:    'images/products/Berry spritz.jpg',
    fragrances: [
      { name: 'Berry Blast',  price: 1199 },
      { name: 'Citrus Punch', price: 999  },
    ],
    sizes: [ { label: '350g', priceAdd: 0 } ],
  },
  {
    id:       11,
    name:     'Blush Orbit',
    category: 'Sculpted',
    emoji:    '🌺',
    tag:      'New',
    image:    'images/products/Blush orbit.jpg',
    fragrances: [
      { name: 'French Lavender',     price: 349 },
      { name: 'Velvet Rose & Oud',   price: 449 },
      { name: 'Peony & Blush Suede', price: 349 },
      { name: 'Mogra',               price: 449 },
      { name: 'Periwinkle',          price: 349 },
      { name: 'Jasmine',             price: 449 },
      { name: 'Fruity',              price: 449 },
      { name: 'Lemongrass',          price: 499 },
    ],
    sizes: [ { label: '130g', priceAdd: 0 } ],
  },
  {
    id:       12,
    name:     'Mango Frost',
    category: 'Container',
    emoji:    '🧊',
    tag:      '',
    image:    'images/products/Mango Frost.jpeg',
    fragrances: [
      { name: 'Mango & Ice', price: 649 },
    ],
    sizes: [ { label: '120g', priceAdd: 0 } ],
  },
  {
    id:       13,
    name:     'Moonlit Garden',
    category: 'Container',
    emoji:    '✨',
    tag:      '',
    image:    'images/products/Moonlit Graden .jpeg',
    fragrances: [
      { name: 'Jasmine & Mogra', price: 950 },
    ],
    sizes: [ { label: '145g', priceAdd: 0 } ],
  },
  {
    id:       14,
    name:     'Morning Meadow',
    category: 'Container',
    emoji:    '🍃',
    tag:      '',
    image:    'images/products/Morning Meadow .jpeg',
    fragrances: [
      { name: 'Lemon Grass', price: 950 },
    ],
    sizes: [ { label: '145g', priceAdd: 0 } ],
  },
  {
    id:       15,
    name:     'Sunset Nectar',
    category: 'Container',
    emoji:    '♥️',
    tag:      'Limited',
    image:    'images/products/Sunset Nectar.jpeg',
    fragrances: [
      { name: 'Peach, Mango & Strawberry', price: 950 },
    ],
    sizes: [ { label: '145g', priceAdd: 0 } ],
  },
  {
    id:       16,
    name:     'Ocean Breeze',
    category: 'Container',
    emoji:    '🌊',
    tag:      'Limited',
    image:    'images/products/Ocean Breeze .jpeg',
    fragrances: [
      { name: 'Fresh Ocean', price: 1200 },
    ],
    sizes: [ { label: '200g', priceAdd: 0 } ],
  },
  {
    id:       17,
    name:     'Arabian Secret',
    category: 'Container',
    emoji:    '🕌',
    tag:      'BestSeller',
    image:    'images/products/Arabian Secret .jpeg',
    fragrances: [
      { name: 'Arabic Fragrance', price: 999 },
    ],
    sizes: [ { label: '145g', priceAdd: 0 } ],
  },
  {
    id:       18,
    name:     'Oud Bloom',
    category: 'Container',
    emoji:    '🌹',
    tag:      'BestSeller',
    image:    'images/products/Oud Bloom.jpeg',
    fragrances: [
      { name: 'Agarwood & Rose', price: 800 },
    ],
    sizes: [ { label: '145g', priceAdd: 0 } ],
  },
  {
    id:       19,
    name:     'Amber Orange',
    category: 'Container',
    emoji:    '🍊',
    tag:      'Limited',
    image:    'images/products/Amber Orange.jpeg',
    fragrances: [
      { name: 'Sun Ripened Orange', price: 800 },
    ],
    sizes: [ { label: '145g', priceAdd: 0 } ],
  },
  {
    id:       20,
    name:     'Twilight Calm',
    category: 'Container',
    emoji:    '🪻',
    tag:      '',
    image:    'images/products/Twilight Calm.jpeg',
    fragrances: [
      { name: 'Calming Lavender', price: 950 },
    ],
    sizes: [ { label: '145g', priceAdd: 0 } ],
  },
];

const siteImages = {
  hero:   'images/products/Hero.png',
  about1: 'images/products/about 1.jpeg',
  about2: 'images/products/about 2.jpeg',
  about3: 'images/products/about 3.jpeg',
};
